language: node_js
node_js:
  - "lts/*"
script:
  - npm run build
  - echo "learn.webpurple.net" > public/CNAME
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  local-dir: public
  project-name: "WebPurple Learn Book"
  on:
    branch: master
